#:schema node_modules/wrangler/config-schema.json
name = "image-generate-app-test"
compatibility_date = "2024-09-03"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[ai]
binding = "AI"
